-- Dummy Smart Engine Assembly System work records for local development.
-- Range: 2026-07-19 through 2026-08-19.
-- Safe to rerun: records generated by this script use barcode prefix DUMMY-YANMAR- and are deleted first.

USE yanmarassy;

SET @seed_today := DATE('2026-08-19');
SET @seed_start := DATE_SUB(@seed_today, INTERVAL 31 DAY);

INSERT INTO engine_models
    (engine_model, description, note, is_deleted)
VALUES
    ('TF65R', 'ASSEMBLY', 'Dummy assembly model', 0),
    ('TF85MR', 'ASSEMBLY', 'Dummy assembly model', 0),
    ('TS230R', 'ASSEMBLY', 'Dummy assembly model', 0)
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    note = VALUES(note),
    is_deleted = VALUES(is_deleted);

INSERT INTO leak_test_judgements
    (judgement_code, judgement_name, result, note, is_deleted)
VALUES
    (1, 'LOW TORQUE NG', 'NG', 'Torque below lower limit', 0),
    (2, 'PASS', 'OK', 'Torque and angle within limits', 0),
    (3, 'HIGH TORQUE NG', 'NG', 'Torque above upper limit', 0),
    (4, 'LOW ANGLE NG', 'NG', 'Angle below lower limit', 0),
    (5, 'HIGH ANGLE NG', 'NG', 'Angle above upper limit', 0),
    (6, 'TOOL ERROR', 'NG', 'Nut runner/controller error', 0)
ON DUPLICATE KEY UPDATE
    judgement_name = VALUES(judgement_name),
    result = VALUES(result),
    note = VALUES(note),
    is_deleted = VALUES(is_deleted),
    updated_at = CURRENT_TIMESTAMP;

DELETE FROM leak_test_work_records
WHERE barcode_scan LIKE 'DUMMY-YANMAR-%'
   OR barcode_scan LIKE 'DUMMY-ASSY-%'
   OR engine_number LIKE 'ASSY-%';

INSERT INTO leak_test_work_records
    (
        engine_model_id,
        engine_number,
        barcode_scan,
        check_date,
        check_time,
        machine_name,
        operator_name,
        parameter_pressure,
        process_no,
        step_no,
        channel_no,
        press_set_up,
        press_set_low,
        pressure_input,
        cycle_time_leak_test_minutes,
        judgement_code,
        created_at,
        updated_at
    )
SELECT
    model.id AS engine_model_id,
    CONCAT(DATE_FORMAT(DATE_ADD(@seed_start, INTERVAL day_numbers.day_offset DAY), '%Y%m%d'), '-', LPAD(slot_numbers.slot_no, 3, '0')) AS engine_number,
    CONCAT('DUMMY-YANMAR-', model.engine_model, '-', DATE_FORMAT(DATE_ADD(@seed_start, INTERVAL day_numbers.day_offset DAY), '%Y%m%d'), '-', LPAD(slot_numbers.slot_no, 3, '0')) AS barcode_scan,
    DATE_ADD(@seed_start, INTERVAL day_numbers.day_offset DAY) AS check_date,
    MAKETIME(7 + FLOOR((slot_numbers.slot_no - 1) / 3), ((slot_numbers.slot_no - 1) * 17 + day_numbers.day_offset * 3) MOD 60, (slot_numbers.slot_no * 11) MOD 60) AS check_time,
    CONCAT('Assembly Station ', 1 + ((slot_numbers.slot_no + day_numbers.day_offset) MOD 4)) AS machine_name,
    ELT(1 + ((slot_numbers.slot_no + day_numbers.day_offset) MOD 5), 'Andi Operator', 'Budi Operator', 'Citra Operator', 'Dewi Operator', 'Eko Operator') AS operator_name,
    24.00 AS parameter_pressure,
    1 + ((slot_numbers.slot_no + day_numbers.day_offset) MOD 12) AS process_no,
    1 + ((slot_numbers.slot_no * 2 + day_numbers.day_offset) MOD 6) AS step_no,
    CONCAT('NR-', LPAD(1 + ((slot_numbers.slot_no + day_numbers.day_offset) MOD 4), 2, '0')) AS channel_no,
    26.00 AS press_set_up,
    22.00 AS press_set_low,
    CASE
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 23) = 0 THEN 20.80
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 29) = 0 THEN 27.30
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 31) = 0 THEN 21.40
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 37) = 0 THEN 26.80
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 41) = 0 THEN 0.10
        ELSE 23.20 + (((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 24) / 10)
    END AS pressure_input,
    6.20 + (((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 45) / 10) AS cycle_time_leak_test_minutes,
    CASE
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 23) = 0 THEN 1
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 29) = 0 THEN 3
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 31) = 0 THEN 4
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 37) = 0 THEN 5
        WHEN ((day_numbers.day_offset * 24 + slot_numbers.slot_no) MOD 41) = 0 THEN 6
        ELSE 2
    END AS judgement_code,
    TIMESTAMP(DATE_ADD(@seed_start, INTERVAL day_numbers.day_offset DAY), MAKETIME(7 + FLOOR((slot_numbers.slot_no - 1) / 3), ((slot_numbers.slot_no - 1) * 17 + day_numbers.day_offset * 3) MOD 60, (slot_numbers.slot_no * 11) MOD 60)) AS created_at,
    TIMESTAMP(DATE_ADD(@seed_start, INTERVAL day_numbers.day_offset DAY), MAKETIME(7 + FLOOR((slot_numbers.slot_no - 1) / 3), ((slot_numbers.slot_no - 1) * 17 + day_numbers.day_offset * 3) MOD 60, (slot_numbers.slot_no * 11) MOD 60)) AS updated_at
FROM (
    SELECT 0 AS day_offset UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
    SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL
    SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL
    SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
    SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL
    SELECT 24 UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
    SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30 UNION ALL SELECT 31
) day_numbers
CROSS JOIN (
    SELECT 1 AS slot_no UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
    SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL
    SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
    SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL
    SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20 UNION ALL
    SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
) slot_numbers
JOIN engine_models model
  ON model.engine_model = ELT(1 + ((slot_numbers.slot_no + day_numbers.day_offset) MOD 3), 'TF65R', 'TF85MR', 'TS230R');

SELECT
    COUNT(*) AS dummy_records,
    MIN(check_date) AS date_from,
    MAX(check_date) AS date_to,
    SUM(CASE WHEN judgement_code = 2 THEN 1 ELSE 0 END) AS ok_records,
    SUM(CASE WHEN judgement_code <> 2 THEN 1 ELSE 0 END) AS ng_records
FROM leak_test_work_records
WHERE barcode_scan LIKE 'DUMMY-YANMAR-%';
